## Discovery addresses population based on amount of replicas
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-discovery-config
  namespace: {{ .Values.namespace }}
data:
  cluster_nodes: |-
    {{- $namespace := .Values.namespace }}
    {{- $replicaCount := .Values.config.broker.replication.count | int }}
    {{- range $i, $e := until $replicaCount }}
    rabbit@rabbitmq-{{ $i }}.rabbitmq-headless.{{ $namespace }}.svc.cluster.local
    {{- if lt (add1 $i) $replicaCount }},{{- end }}
    {{- end }}
---
## RabbitMQ main discovery service
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespace }}
  labels:
    app: rabbitmq
spec:
  type: {{ .Values.config.broker.network.serviceType }}
  ports:
  - port: 5672
    name: amqp
  - port: 15672
    name: management
  selector:
    app: rabbitmq

---
## RabbitMQ internal cluster discovery service
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: {{ .Values.namespace }}
  labels:
    app: rabbitmq
spec:
  clusterIP: None
  ports:
  - port: 5672
    name: amqp
  - port: 15672
    name: management
  selector:
    app: rabbitmq

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespace }}
  labels:
    app: rabbitmq
spec:
  {{- with .Values.config.broker }}
  replicas: {{ .replication.count }}
  selector:
    matchLabels:
      app: rabbitmq
  serviceName: rabbitmq-headless
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rabbitmq
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: fix-paths-permissions
        image: busybox
        command: ['sh', '-c', 'chown 999:999 -R /var/lib/rabbitmq /var/log/rabbitmq'] # /etc/rabbitmq
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
          subPath: {{ .storage.local_subpath }}/var/lib/rabbitmq
        - name: rabbitmq-data
          mountPath: /var/log/rabbitmq
          subPath: {{ .storage.local_subpath }}/var/log/rabbitmq
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
          subPath: {{ .storage.local_subpath }}/var/lib/rabbitmq
        - name: rabbitmq-data
          mountPath: /var/log/rabbitmq
          subPath: {{ .storage.local_subpath }}/var/log/rabbitmq
        env:
        - name: RABBITMQ_ERLANG_COOKIE
          value: {{ .replication.clusterAuth }}
        - name: RABBITMQ_USE_LONGNAME
          value: "true"
        - name: RABBITMQ_CLUSTER_NODES
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-discovery-config
              key: cluster_nodes
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: broker-data-pvc
  {{- end }}