{{- with .Values.config.broker.storage }}
## RabbitMQ datadir storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: broker-data-storage-class
  namespace: {{ $.Values.namespace }}
provisioner: {{ .provisioner }}
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: broker-data-pv
  namespace: {{ $.Values.namespace }}
spec:
  
  capacity:
    storage: {{ .pv_size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: broker-data-storage-class
  local:
    path: {{ .local_path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: persistence-managed-replicas
              operator: Exists
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: broker-data-pvc
  namespace: {{ $.Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .pvc_size }}
  storageClassName: broker-data-storage-class
{{- end }}