## RabbitMQ persistent storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: broker-storage-class
  namespace: {{ .Values.namespace }}
provisioner: {{ .Values.config.broker.storage.provisioner }}
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: broker-pv
  namespace: {{ .Values.namespace }}
  labels:
    type: local
    usage: redis
spec:
  capacity:
    storage: {{ .Values.config.broker.storage.pv_size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: broker-storage-class
  local:
    path: {{ .Values.config.broker.storage.local_path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: persistence-managed-replicas
              operator: Exists
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: broker-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce  # Should match PV access mode
  resources:
    requests:
      storage: {{ .Values.config.broker.storage.pvc_size }}
  storageClassName: broker-storage-class