{{- with .Values.config.cache }}
## Redis persistent storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cache-storage-class
  namespace: {{ $.Values.namespace }}
provisioner: {{ .storage.provisioner }}
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cache-pv
  namespace: {{ $.Values.namespace }}
  labels:
    type: local
    usage: redis
spec:
  capacity:
    storage: {{ .storage.pv_size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cache-storage-class
  local:
    path: {{ .storage.local_path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: persistence-managed-replicas
              operator: Exists
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-pvc
  namespace: {{ $.Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce  # Should match PV access mode
  resources:
    requests:
      storage: {{ .storage.pvc_size }}
  storageClassName: cache-storage-class
{{- end }}