apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sentinel
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.config.cache.replication.count }}
  selector:
    matchLabels:
      app: redis-sentinel
      role: sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
        role: sentinel
    spec:
      containers:
        - name: redis-sentinel
          image: redis:latest
          command: ["redis-sentinel", "--sentinel", "monitor", "mymaster", "redis-main", "6379", "2", "DOWN"]
          ports:
            - containerPort: 26379
      nodeSelector: # Allow only on nodes with "persistence-managed-replicas" label
        persistence-managed-replicas: "true"
      affinity:
        podAntiAffinity: # Limit number of pods of the same type to 1 per node
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - redis-sentinel
            topologyKey: "kubernetes.io/hostname"
